name: quote_widget_app
description: Random image and quote app with home screen widget.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  home_widget: ^2.0.0
  workmanager: ^0.5.2
  sqflite: ^2.3.3
  http: ^1.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  sqflite_common_ffi: ^2.3.4

flutter:
  uses-material-design: true
  assets:
    - assets/quotes.json
    - assets/images/
